### ISSUE TITLE
clickable URLs in diagrams

### ISSUE THREAD

**Issue by janekska** [schplurtz/a2s#2]
Hi!

Nice plugin!
Thank you for your work.

Are there any ability to put clickable links into a diagram?
F.ex.:

```
#----------------.
|[grbx]          |        .------.
| a kinda of box +=======>|outbox|
|                |        '------'
'----------------#

[grbx]: {"fill":"#009900","a2s:delref":true,"url":"http://www.mysite.net"} 
```

**Comment by schplurtz** [comment]
Hi,

Thank you for your interest in this project and for your suggestion.

Unfortunately, there is currently no such feature. The code that handles the drawing is entirely from [dhobsd/asciitosvg](https://github.com/dhobsd/asciitosvg), and I don't understand the most part of it. I just made the code available to DokuWiki. As I can see that you've already [asked dhobsd](https://github.com/dhobsd/asciitosvg/issues/5), I'll close this feature request now.

I'll be happy to import any upstream evolution when there are some.

**Comment by janekska** [comment]
I did second attempt after a while and now right. :)

I got it working and create pull request for dhobsd/asciitosvg/pull/6

**Comment by schplurtz** [comment]
Great ! I'll import the updated asciitosvg code when your PR is accepted.

By the way, this [W3C wiki](https://www.w3.org/wiki/SVG_Links) page suggests you should use `xlink:href="..."`.

Schplurtz

**Comment by schplurtz** [comment]
Links are available now. external links and also wiki links
